name: GitHub-Profile-3D-Contrib

on:
  schedule: # 08:00 IST == 2:30 UTC
    - cron: "30 2 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: generate-github-profile-3d-contrib
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate 3D Contribution Profile
        uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}  
          USERNAME: ${{ ADIII-Archives }}

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add -A .
          git diff --cached --quiet || (
            git commit -m "generated"
            git push
          )
